name: online_shop_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.4
  logger: ^2.0.2+1
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  responsive_sizer: ^3.2.0
  riverpod_annotation: ^2.2.1
  riverpod_generator: ^2.3.5
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  flutter_slidable: ^3.0.0
  in_app_notification: ^1.1.2
  intl: ^0.18.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  riverpod_lint: ^2.3.2

flutter:
  uses-material-design: true
  fonts:
    - family: Kodchasan
      fonts:
        - asset: assets/fonts/Kodchasan.ttf
  assets:
    - assets/mock/banners.json
    - assets/mock/products.json
    - assets/mock/my_banners.json
    - assets/mock/my_products.json
